import type { AppProps } from 'next/app'
import type { Metadata } from 'next'
import { useRouter } from 'next/router'
import { motion, AnimatePresence } from 'framer-motion'

import Header from '../components/header'

import '../styles/global.css'

export const metadata: Metadata = {
  title: 'Kim Nguyen',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter()
  return (
    <AnimatePresence mode='wait'>
      <motion.div key={router.pathname}> 
        <Header></Header>
        <Component {...pageProps} />

        <motion.div className='slide-in' initial={{ scaleY: 0 }}
                                          animate={{scaleY: 0 }}
                                          exit={{ scaleY: 1 }}
                                          transition={{duration: 1, ease : [0.22, 1, 0.36, 1] }}
        ></motion.div>
        <motion.div className='slide-out' initial={{ scaleY: 1 }}
                                          animate={{scaleY: 0 }}
                                          exit={{ scaleY: 0 }}
                                          transition={{duration: 1, ease : [0.22, 1, 0.36, 1] }}
        ></motion.div>
      </motion.div>
    </AnimatePresence>
  )
}